=== FrancisVarga/fdt-ressources/projectTypes/projectType.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://fdt.powerflasher.com/ProjectType"
	xmlns:tns="http://fdt.powerflasher.com/ProjectType">
	<element name="projectType">
		<complexType>
			<sequence>
				<element name="name" type="string"></element>
				<element name="description" type="string"></element>

				<element name="compatibleSdks">
					<complexType>
						<sequence>
							<element name="sdk" type="tns:Sdk" minOccurs="1"
								maxOccurs="unbounded"></element>
						</sequence>
					</complexType>
				</element>
				<element name="swcs">
					<complexType>
						<sequence>
							<element name="swc" type="tns:Swc" minOccurs="1"
								maxOccurs="unbounded"></element>
						</sequence>
					</complexType>
				</element>

				<element name="runtime" type="tns:Runtime"></element>
				<element name="compatiblePlayers">
					<complexType>
						<sequence>
							<element name="player" type="tns:Player" minOccurs="0"
								maxOccurs="unbounded"></element>
						</sequence>
					</complexType>
				</element>
				<element name="compilerArguments" type="tns:CompilerArguments"></element>
			</sequence>
		</complexType>
	</element>

	<simpleType name="SimplePlayer">
		<restriction base="string">
			<enumeration value="Standalone Flash Player"></enumeration>
			<enumeration value="Browser"></enumeration>
			<enumeration value="External SWF Viewer"></enumeration>
			<enumeration value="AIR Debug Launcher"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="Player">
		<simpleContent>
			<extension base="tns:SimplePlayer">
				<attribute name="default" type="boolean" use="required"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="SimpleCompilerArguments">
		<sequence>
			<element name="argument" type="string" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="CompilerArguments">
		<complexContent>
			<extension base="tns:SimpleCompilerArguments">
				<attribute name="passClasspath" type="boolean" use="required"></attribute>
				<attribute name="passSwcs" type="boolean" use="required"></attribute>
				<attribute name="passMainclass" type="boolean" use="required"></attribute>
				<attribute name="passRsls" type="boolean" use="required"></attribute>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Sdk">
		<attribute name="min" use="required"></attribute>
		<attribute name="max" use="optional"></attribute>
	</complexType>

	<complexType name="Swc">
		<sequence>
			<element name="path" type="string"></element>
		</sequence>
	</complexType>

	<simpleType name="Runtime">
		<restriction base="string">
			<enumeration value="Flash Player"></enumeration>
			<enumeration value="AIR"></enumeration>
		</restriction>
	</simpleType>

</schema>

=== FrancisVarga/fdt-ressources/projectTypes/flex4air.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:projectType xmlns:tns="http://fdt.powerflasher.com/ProjectType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fdt.powerflasher.com/ProjectType projectType.xsd ">
	<name>Flex 4 AIR</name>
	<description>Flex 4 AIR Project Type</description>
	<compatibleSdks>
		<sdk min="4" max="4" />
	</compatibleSdks>
	<swcs>
		<swc>
			<path>frameworks/libs/air/airglobal.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/textLayout.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/framework.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/spark.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/rpc.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/datavisualization.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/sparkskins.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/utilities.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/air/airframework.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/air/airspark.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/air/applicationupdater.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/air/applicationupdater_ui.swc</path>
		</swc>
        <swc>
			<path>frameworks/libs/air/servicemonitor.swc</path>
		</swc>
	</swcs>
	<runtime>AIR</runtime>
	<compatiblePlayers>
		<player default="true">AIR Debug Launcher</player>
	</compatiblePlayers>
	<compilerArguments passClasspath="true" passMainclass="true" passSwcs="true" passRsls="false">
		<argument>-target-player={playerVersion}</argument>
		<argument>-library-path+="{flexSDK}/frameworks/locale/en_US"</argument>
		<argument>-default-size=550,400</argument>
	</compilerArguments>
</tns:projectType>

=== FrancisVarga/fdt-ressources/projectTypes/as3air.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:projectType xmlns:tns="http://fdt.powerflasher.com/ProjectType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fdt.powerflasher.com/ProjectType projectType.xsd ">
	<name>AS 3 AIR</name>
	<description>This project type defines a pure AS3 project for Adobe Integrated Runtime (AIR). 
It contains basic libraries according to the selected SDK and Flash Player version. No special compiler arguments are defined.</description>
	<compatibleSdks>
		<sdk min="3"/>
	</compatibleSdks>
	<swcs>
		<swc>
			<path>frameworks/libs/air/airglobal.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/flex.swc</path>
		</swc>
	</swcs>
	<runtime>AIR</runtime>
	<compatiblePlayers>
		<player default="true">AIR Debug Launcher</player>
	</compatiblePlayers>
	<compilerArguments passClasspath="true" passMainclass="true" passSwcs="true" passRsls="false">
		<argument>-static-link-runtime-shared-libraries=true</argument>
		<argument>-target-player={playerVersion}</argument>
		<argument>-library-path+="{flexSDK}/frameworks/locale/en_US"</argument>
		<argument>-default-size=550,400</argument>
	</compilerArguments>
</tns:projectType>

=== FrancisVarga/fdt-ressources/projectTypes/as3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:projectType xmlns:tns="http://fdt.powerflasher.com/ProjectType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fdt.powerflasher.com/ProjectType projectType.xsd ">
	<name>AS 3</name>
	<description>This project type defines a pure AS3 project for Flash Player. 
It contains basic libraries according to the selected SDK and Flash Player version. No special compiler arguments are defined.</description>
	<compatibleSdks>
		<sdk min="3"/>
	</compatibleSdks>
	<swcs>
		<swc>
			<path>frameworks/libs/player/{playerVersion}/playerglobal.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/flex.swc</path>
		</swc>
	</swcs>
	<runtime>Flash Player</runtime>
	<compatiblePlayers>
		<player default="true">External SWF Viewer</player>
		<player default="false">Browser</player>
		<player default="false">Standalone Flash Player</player>
	</compatiblePlayers>
	<compilerArguments passClasspath="true" passMainclass="true" passSwcs="true" passRsls="false">
		<argument>-static-link-runtime-shared-libraries=true</argument>
		<argument>-target-player={playerVersion}</argument>
		<argument>-library-path+="{flexSDK}/frameworks/locale/en_US"</argument>
		<argument>-default-size=550,400</argument>
	</compilerArguments>
</tns:projectType>

=== FrancisVarga/fdt-ressources/projectTypes/flex4.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:projectType xmlns:tns="http://fdt.powerflasher.com/ProjectType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fdt.powerflasher.com/ProjectType projectType.xsd ">
	<name>Flex 4</name>
	<description>Flex 4 Project Type</description>
	<compatibleSdks>
		<sdk min="4" max="4" />
	</compatibleSdks>
	<swcs>
		<swc>
			<path>frameworks/libs/player/{playerVersion}/playerglobal.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/flex.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/textLayout.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/framework.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/rpc.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/spark.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/sparkskins.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/utilities.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/datavisualization.swc</path>
		</swc>
	</swcs>
	<runtime>Flash Player</runtime>
	<compatiblePlayers>
		<player default="true">External SWF Viewer</player>
		<player default="false">Browser</player>
		<player default="false">Standalone Flash Player</player>
	</compatiblePlayers>
	<compilerArguments passClasspath="true" passMainclass="true" passSwcs="true" passRsls="false">
		<argument>-target-player={playerVersion}</argument>
		<argument>-library-path+="{flexSDK}/frameworks/locale/en_US"</argument>
		<argument>-default-size=550,400</argument>
	</compilerArguments>
</tns:projectType>

=== FrancisVarga/fdt-ressources/projectTypes/flex3air.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:projectType xmlns:tns="http://fdt.powerflasher.com/ProjectType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fdt.powerflasher.com/ProjectType projectType.xsd ">
	<name>Flex 3 AIR</name>
	<description>This project type defines a Flex project for Adobe Integrated Runtime (AIR).
It contains all necessary libraries according to the selected SDK and Flash Player version. No special compiler arguments are defined.</description>
	<compatibleSdks>
		<sdk min="3" max="3" />
	</compatibleSdks>
	<swcs>
		<swc>
			<path>frameworks/libs/air/airglobal.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/air/airframework.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/air/applicationupdater_ui.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/air/servicemonitor.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/flex.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/framework.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/rpc.swc</path>
		</swc>
		<swc>
			<path>frameworks/libs/utilities.swc</path>
		</swc>
	</swcs>
	<runtime>AIR</runtime>
	<compatiblePlayers>
		<player default="true">AIR Debug Launcher</player>
	</compatiblePlayers>
	<compilerArguments passClasspath="true" passMainclass="true" passSwcs="true" passRsls="false">
		<argument>-target-player={playerVersion}</argument>
		<argument>-library-path+="{flexSDK}/frameworks/locale/en_US"</argument>
		<argument>-default-size=550,400</argument>
	</compilerArguments>
</tns:projectType>
